Routes to handle mentions timeline
hngi/expense-bot pull request #17
Opened 2020-06-22 10:07 UTC by Lihemen

### Change proposed in this pull request

- [ ] feat: getting all mentions on the timeline
- [ ] feat: automatically retweet of random mention on timeline
- [ ] feat: sending automatic random reply to mention on timeline
- [ ] bug: sending error message for routes not created

2020-06-22 18:07 UTC, piouson requested changes
Overall your development environment has changed the formatting of all the files in this project, spacing, tabs, etc..
I will implement linting/prettier now so that we can all keep the same formatting..

2020-06-22 18:07 UTC, piouson commented on server.js
> +app.get('/api/timeline/mentions/reply', replyMentions);
route `/api/timeline/mentions` and function `getMentions` is not required

2020-06-22 18:07 UTC, piouson commented on server.js
> +app.get('/api/timeline/mentions/retweet', retweetMention);
route `/api/timeline/mentions/retweet` and function `retweetMention` is not required
normally, a `retweet` action would've required a `POST` route

2020-06-22 18:07 UTC, piouson commented on server.js
> +app.get('/api/timeline/mentions', getMentions);
although not part of your original user story, we can refactor this to `/api/tweets/timeline` and build on it to retrieve the bot's timeline..
if you wish to work on this, remove from this PR, create a new user story about *timeline endpoint* and create a new issue to go with this so you can begin..

2020-06-22 18:07 UTC, piouson commented on src/api/mentions.js
> +function replyMention(req, res) {
we already have `src/api/reply.js` that should handle all replies and this file exports module `reply` which we should all use for replies..
you can make improvements to `reply.js` but this will require a different Issue and User Story
you should `require` the existing module for re-use instead of creating a new `replyMention` function.

2020-06-22 18:07 UTC, piouson commented on server.js
> +const replyMentions = require('./src/api/mentions');
if you exported all three as array, you can import with destruturing
```
const [replyMentions, retweetMention, getMention] = require('./src/api/mentions');
```

2020-06-22 18:07 UTC, piouson commented on src/api/mentions.js
> +module.exports = (replyMention, retweetMention, getMentions);
you can export as object or array, then easily import all in one by destructuring
```
module.exports = [replyMention, retweetMention, getMentions];
---
// in another file
const [replyMention, retweetMention, getMentions] = require('./src/api/mentions');
```

2020-06-22 18:07 UTC, piouson commented on package-lock.json
> +    "@sindresorhus/is": {
your `package-lock.json` has changes that are not required by this project. you will need to clean this up or remove from your next commit

2020-06-23 07:54 UTC, Lihemen commented on server.js
> +app.get('/api/timeline/mentions/retweet', retweetMention);
Alright doing that

2020-06-23 08:24 UTC, closed without merging